---
- name: Create
  hosts: hypervisor
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  become: yes
  tasks:

    # TODO: Developer must implement and populate 'server' variable
    - include_role:
        name: molecule_libvirt
        tasks_from: create.yml

    - when: server.changed | default(false) | bool
      block:
        - name: Populate instance config dict
          set_fact:
            instance_conf_dict: {
              'instance': "{{ item.instance }}",
              'address': "{{ item.address }}",
              'user': "{{ item.user | default('') }}",
              'port': "{{ item.port | default('') }}",
              'connection': "{{ item.connection | default('') }}",
              'identity_file': "{{ item.identity_file | default('') }}", }
          with_items: "{{ server.results }}"
          register: instance_config_dict

        - name: Convert instance config dict to a list
          set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_json | from_json | to_yaml }}
            dest: "{{ molecule_instance_config }}"
            mode: 0600
          delegate_to: localhost
