---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    login_cmd_template: 'virsh -c qemu+ssh://${HYPERVISOR_ANSIBLE_USER}@${HYPERVISOR_ANSIBLE_HOST}/system console {instance}'
platforms:
  - name: ubuntu1804
    os: ubuntu
    version: 1804

  - name: ubuntu2004
    os: ubuntu
    version: 2004

  - name: ubuntu2110
    os: ubuntu
    version: 2110

  - name: ubuntu2204
    os: ubuntu
    version: 2204
provisioner:
  name: ansible
  playbooks:
    create: ../../../setup/molecule/default/create.yml
    prepare: ../../../setup/molecule/default-install/converge.yml
    destroy: ../../../setup/molecule/default/destroy.yml
    converge: ../default-deploy/converge.yml
    verify: ../default-deploy/verify.yml
  inventory:
    hosts:
      hypervisor:
        hosts:
          hypervisor-1:
            ansible_user: ${HYPERVISOR_ANSIBLE_USER}
            ansible_host: ${HYPERVISOR_ANSIBLE_HOST}
            ansible_connection: ${HYPERVISOR_ANSIBLE_CONNECTION}
            ansible_ssh_pass: ${HYPERVISOR_ANSIBLE_PASSWORD}
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
verifier:
  name: ansible
